### ISSUE TITLE
Mounts table changes column width as filters or pages change

### ISSUE THREAD

**Issue by sofia819** [sofia819/mount_recorder_client#16]
**Describe the bug**
- When a user changes the expansions checked in the filter or the page number, the column widths change.

**To Reproduce**
1. Go to `Mounts` tab.
2. Click on `A Realm Reborn` checkbox to un-check it.
3. See that the column widths change.
4. Go to the next page in the table.
5. See that the column widths change.

**Expected behavior**
- Column widths should be fixed.

**Screenshots**
![gif](https://user-images.githubusercontent.com/17885737/92429900-55b0e700-f161-11ea-9f6a-c73774018a57.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.83

**Additional context**

**Comment by sofia819** [comment]
I am suggesting a new approach of wrapping the content of which you want to have fixed height and width with the following:
 ```
<Box
  width='100px'
  height='80px'
  justifyContent='center'
  alignItems='center'
  overflow='hidden'
  display='flex'
  margin='auto'
>
{ // ...content in the user column}
</Box>
```

You can make this a new component and pass it children props.

Places I think you should use this wrapper:
- Edit user mounts button in user mounts tab
- Mount name column in user mounts tab
- Mount name content in mounts tab
- Expansion name content in mounts tab

![image](https://user-images.githubusercontent.com/17885737/94376628-b3de4380-00e9-11eb-96d4-36b9a2a0bda3.png)
![image](https://user-images.githubusercontent.com/17885737/94376651-dd976a80-00e9-11eb-89b8-9f38cdb61b09.png)

**Comment by EvanM27** [comment]
Got a basic design implemented that functions well and just as suspected with the EditUsernameButton wrapped the cells remain in position when rows/pages change

**Comment by EvanM27** [comment]
There is a bug that occurs specifically with Shadowbringers expansion on mount table, where you can see the edge being clipped by the 100px
