### ISSUE TITLE
Users table changes column width as pages change

### ISSUE THREAD

**Issue by sofia819** [sofia819/mount_recorder_client#17]
**Describe the bug**
- When a user changes the page number, the column widths change.

**To Reproduce**
1. Go to `Users` tab.
2. Go to the next page in the table.
3. See that the column widths change.

**Expected behavior**
- Column widths should be fixed.

**Screenshots**
![gif](https://user-images.githubusercontent.com/17885737/92429948-7aa55a00-f161-11ea-9a79-e8498f655c1f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.83

**Additional context**
- This issue can be ignored if the `Username` and `Edit` columns are combined in [issue 2](https://github.com/sofia819/mount_recorder_client/issues/2)

**Comment by EvanM27** [comment]
Only one column exists now due to [issue 2](https://github.com/sofia819/mount_recorder_client/issues/2) combining the username with edit button
