### ISSUE TITLE
Instructions for using the website on each tab

### ISSUE THREAD

**Issue by sofia819** [sofia819/mount_recorder_client#4]
**Is your feature request related to a problem? Please describe.**
- There is no instructions on how to use the website.

**Describe the solution you'd like**
- Add tool tips and instructions on each tab as needed.

**Describe alternatives you've considered**
- N/A.

**Additional context**
- N/A.

**Comment by EvanM27** [comment]
A help tab for more detailed instructions than tooltips, and to help keep other pages clear of instructions cluttering UI
